const _SELENIUM_STANDALONE_HOST = '127.0.0.1';
const _SELENIUM_STANDALONE_PORT = 4444;

const _TEST_TARGET_SITE = 'http://www.google.com';
const _TEST_KEY_SEARCH = 'webdriver';
const _GOOGLE_SUBMIT_SEARCH_BUTTON_ID = 'btnG';

module.exports = {
    HOST: _SELENIUM_STANDALONE_HOST,
    PORT: _SELENIUM_STANDALONE_PORT,
    TARGET_SITE: _TEST_TARGET_SITE,
    TEST_KEY_SEARCH: _TEST_KEY_SEARCH,
    SUBMIT_SEARCH_BUTTON_ID: _GOOGLE_SUBMIT_SEARCH_BUTTON_ID
}